apiVersion: v1
kind: Namespace
metadata:
  name: contacts
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api
  namespace: contacts
  labels:
    app: contacts
spec:
  selector:
    matchLabels:
      app: contacts
  replicas: 3
  template:
    metadata:
      labels:
        app: contacts
    spec:
      containers:
      - name: api-server
        image: johnbelamaric/contacts-api
        imagePullPolicy: Always
        args:
        - -dsn
        - api:mypassword@tcp(mysql.db:3306)/contacts?charset=utf8&parseTime=True
        - -s
        - :443
        - -cert
        - /etc/certs/tls.crt
        - -key
        - /etc/certs/tls.key
        ports:
        - containerPort: 443
          name: https
          protocol: TCP
        volumeMounts: 
        - name: contacts-tls
          mountPath: /etc/certs
          readOnly: true
      volumes:
      - name: contacts-tls
        secret:
          secretName: contacts-tls
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: contacts
  labels:
    app: contacts
spec:
  type: NodePort
  selector:
    app: contacts
  ports:
  - name: https
    port: 443
    protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api
  namespace: contacts
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/secure-backends: "true"
    ingress.kubernetes.io/secure-verify-ca-secret: ca
spec:
  tls:
  - hosts:
    - minikube.local
    secretName: minikube
  rules:
  - host: minikube.local
    http:
      paths:
      - path: /contacts
        backend:
          serviceName: api
          servicePort: 443
---
apiVersion: v1
kind: Secret
metadata:
  name: minikube
  namespace: contacts
type: kubernetes.io/tls
data:
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBd01QQ1N3WWVKQXRHenhhMGZNQjB2OWhqb0E1bUkvUUx2RnlGalU0TzNsZFdEd2JhCkgvaUJ2SWpFQjM1NWZVNDM5V1E1T3JRWjNqRmNMaVpDWHkvNGwyWWlOTnFjdTV2Q1V1SVQ1UWdlamk5ZXp2aXAKbDE2bWxkWnJleUlNUFV3WWxzMVVJQ0ZONGpoN21VU2ZuaXAzSzByM0M5SHI4Y3NmVzJYUlErV2kxMWVxS2ZVcgpzTzRuc0crNFpwZjlJSWFDeHp3QlU0VzBNNVRlL2hmTFB5NUIrejJkMk00NkM3Q1dKcWdmc2czUXRCMWN5S2FICm5GWlJJTk5CbzN5WTNZaitkdzcyMko4TFRlUFFGbkVoZ1FTd2puSmNhMFJQNnJhMzJlMmhYZHVBWlFnYlVjSDEKZUR3UEJJQzFITk5QYVRoS0d3YWdYTklUYWFuU1kvYlNWZE1YMVFJREFRQUJBb0lCQUdPY1JTaVRycnVkZ0NlLwphZUVWYXI5QVNLc0xCY2tLY1k0U21ZamRqMTFoOER5dm84UGxuTlVhTDRKWDN0dmJzWnNEQVhmT1haZXVGaDVhCjh1MVJVcnFac285eGNKQ1orcDd0NkszdnRpcHZYQ1RENW84c0FCVnB5ZnpGS1dIN2tyRkt4WEFkQmF3aTErdnAKeERudFk4dGhYNndoL0RUa2EvM0U3WkNTZDhXaXg4MXhSeWo1ZWRoVU1NVWtBSmZvS0ZIdDZaMEUrcmFDUk16bwo4ZWtOZ01ySUlGeGN6V2doTHV3b0xhU1MzZVJkMVFaLzBuQ2FFb2d1dC9yUHRQdWlGa0x4THdDbWNmUUQwcDdjCkxVQlFjTzFQR3lGUjNSUThFeW1jMWF0elJYRldMRE8zaVl2d1huL20rMHV5a1luOVlMdzFERlVJcWVWTXd3c00KOEFjRUx2a0NnWUVBNHhmOEtyS3FQVm9PQ3VjQmQxamtrNEQ0ZTIyUFFLOWY4QVRLc1luYVEycTlkeFA5U3hqVgozVUZmYitCalg4RGZZTjcrYmZ4TzBDTW8zaGdmeTQxS0N2TlZVOU0rYXhPTnVnVDlwRTFSUlFMdDZRWlM0OTVTCllEL3JOaitRMWNwSTNpKzBnTXBzQnJpSGo2L1I0SERmRkNnamJpQzFGa0lCOUR4dEkvMk1QSmNDZ1lFQTJVMGoKVU5UbGdvVlM3ZEV3K1dmMUpRanROeXR4UXBUKzgyekRLMExENXVySDRUQ3hPMW1jR0FhUS9BcFRZc28rT3dPegpBaXhhd0p0eWExVjduV2lBdTNLZGhGalYwYmpaUzBlaEpWUit1UnEwSGFPMUNUKzEwZUd6Y2Y2N2dPTmc5c0gyClFTeXIvSitSRzN6bFpRU2FRb0FNdVBCd0pmSFVTSGZ3Q2lUbklITUNnWUVBMU5GQWJ4ODZiUDU5RkhpQ0pqOTMKRGtpYUZNbUtxenJ1OUhiNUlVSW4rbkFJbUpSeUZqTnpFTU5YMWZkNkNWMHR1WkdnN0orN21GQ3ExdC9TeENabgpraldSN0ZtV01EQ0Y3Q01MTkRPRkN1Q0E1cFVYanhabEtuQWNWSjFqZFFiNkhNYW1LT0FLTm80dDlGajNuWmNKClo5RnB5cVg2THA2elNCaHN5NEtzTG9jQ2dZQlp5OENPUkl2YkZkRWhLVkw5blhIMkxld280akRaZk15bU53bW4KdE4xVGJTM1A1dGsyVjE5anBrTC9oQnpWTkJIblBTNFo5YzVDelhuSTFQaFNJYjhndHNwVXlJa0RNMG5JQy8rUgpkNHN1WHRTVGN2VDZyM01wR2dXWFU5YVQrbUkxVmcyMi9Rak5TZnNpeXNmWXFNQStQc0FESklpVGhZMWRyUUpxCmpybGI5UUtCZ0V5MGxuMXFWa3crMDF5TVZpV3ZFRGxubUNPU1A3dThYaUNqRCswanU0U3FqZGl4dVZQQm9BZVQKaEsvR1ZSeW9PeDA1Y3d2S0FKaDljajRIYUZhYmhGRXNUL0tFTHZ3S1ZwN2hzSjY2cEFwenhlaVZ5V2czWFl0QgpaZEF1MHh0ZkRpYzBrN0p1WElwMG1RaCtEOW1yR1A0dmJLRXRWUGxSWko1WmJFdUhlZGkvCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM3VENDQWRXZ0F3SUJBZ0lKQVBqUVBZYVF1Zm1STUEwR0NTcUdTSWIzRFFFQkJRVUFNQmd4RmpBVUJnTlYKQkFNVERXNW5jQzF3Y21sdFpYSXRZMkV3SGhjTk1UY3dOekV4TVRrME1UVXdXaGNOTXpFd016SXdNVGswTVRVdwpXakFUTVJFd0R3WURWUVFEREFodGFXNXBhM1ZpWlRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDCkFRb0NnZ0VCQU1ERHdrc0dIaVFMUnM4V3RIekFkTC9ZWTZBT1ppUDBDN3hjaFkxT0R0NVhWZzhHMmgvNGdieUkKeEFkK2VYMU9OL1ZrT1RxMEdkNHhYQzRtUWw4ditKZG1JalRhbkx1YndsTGlFK1VJSG80dlhzNzRxWmRlcHBYVwphM3NpREQxTUdKYk5WQ0FoVGVJNGU1bEVuNTRxZHl0Szl3dlI2L0hMSDF0bDBVUGxvdGRYcWluMUs3RHVKN0J2CnVHYVgvU0NHZ3NjOEFWT0Z0RE9VM3Y0WHl6OHVRZnM5bmRqT09ndXdsaWFvSDdJTjBMUWRYTWltaDV4V1VTRFQKUWFOOG1OMkkvbmNPOXRpZkMwM2owQlp4SVlFRXNJNXlYR3RFVCtxMnQ5bnRvVjNiZ0dVSUcxSEI5WGc4RHdTQQp0UnpUVDJrNFNoc0dvRnpTRTJtcDBtUDIwbFhURjlVQ0F3RUFBYU0vTUQwd0NRWURWUjBUQkFJd0FEQUxCZ05WCkhROEVCQU1DQmVBd0l3WURWUjBSQkJ3d0dvSUliV2x1YVd0MVltV0NEbTFwYm1scmRXSmxMbXh2WTJGc01BMEcKQ1NxR1NJYjNEUUVCQlFVQUE0SUJBUUNFT3cyUDRUekhDVVF6UnkyekcrV3k0aEtGd1cyY2lONmt4NFJ4Q0hhSQpDdGViRStjajBiRnl2Z085Wk1XMzFyMGFFaUdpLzBZWjZ4T2tqUklyM0ZiazJzNFhwY3BIWVRGbE85NnAzS0QrCmVXckZiWmZ3NGRYT3dKQm9XN1VEaWRpUmNNaEJUb0ljVTdXRGMzQUlEYUk1cm1vWnZ3WUY5eVJqOUFQZWpnREwKZTNCOHVtMzdVYnY2QWRvN0lVT0tDandNYjZJTUsyS0RVVkp4Wm9iY3FKb1NUMzI3Qzlxb29Ycll0WklzczNRQwpNTkZrNmF3UGNOS0gvWnI4cmZ5UDdpcmN3RkZvSFN4M2ZrZko5WmNWd2M4eTEwa2VqU3I2ZmxpRlNjY1ZlRTZxCllXemRLSUM1UXhra01qT1hVYzYrSTM1ZDg0NHl2TzJQaFBOUDErL2xYd1lCCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
---
apiVersion: v1     
kind: Secret
metadata:
  name: contacts-tls
  namespace: contacts
type: kubernetes.io/tls
data:
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBcjZ5UWtpVmxsNHJlRUx1VVJoTXhkaEpvZUZ0RHc4WjBVbitnRTk3MHJrMjM4SFV6Cjk0dEIyTzg4RXhtbCtwZnhkaVJGZjRkTEV2SVdISzdJd2pHRkpxYURVYndwWFJhUHhybjRQcnZYa09GNktoVWwKZndjOTAwbVRsSm0wZE5HWUFHVVlzL1lwVGNDNG0vS2R4RjdWbHFFdjk4Smp6VFlZMm05SzF5S2FMWnlXSU1kbwpEUWgraSt0NWJjekh2VVNXYzVXSTh5c0ZLQ3VXeU11UTJhOEh0K01UMVZhVWdnQlJvUlN6WXU4WDF4SXQwRlplCjlFRVVmWG5kdFgveW5DSHQrcWtvWUxkTWF2YkVKaWFaSDJUelVEVWxpSFJCNFJRZ3JFcmpXTmF3MTduUitMbHQKcVhwU1ppQmhmNVd1Yzl5MFl3K1oxYnlzSGN2M0FXdWVlLzlONXdJREFRQUJBb0lCQUVhZHIxK1ArTTU1MjlvTwpEUVErSXR1N2VwTW0zSTZONzZSWitSY0R3SWR3WmtnYVZORmxBUXNhMzZNdDVESmZjWWh6L0J2UFhyWTI2ZnlOCnBkV3A0a1F2R3dwNEFJaVMwU2lwQ01qdTZUQXI4dGVIdUpMZmJsTEllTEo3TnJiZXFhTS9BRGNXOUhOMHpNQ2oKUGhmNXB4SHRxVUtHdVdkOEgzRnUyejZ2Z2hwaTlOYTNyN2U2K0JNaFhLcW5sTWFjZGphaHJtTk5lSzMxcVdtZQpPc3lrOFUrd2RzNmk1ODdSZnV2QWpiQkc4WVRWaElWUENINWxYc05EY3FLclUwWFRvS0ZzR054MVFXTjlGMEJBCkcxUkp3YXZTSEtLNXlyQUZFQWNuY0FJeUI1MWpPMTdJQU81ajZEVEZWdDJOWk45Nmd3UWVUK1BCYzJEZWNxZlcKcWpJYUUwRUNnWUVBMWJvdk1Ed095RXZUWFpCMEp3eUZyQ0VGRjRIRnlHVC9RTG0rRUxoaFhyTkpQVlp2ZnllWgpaVWdGZmhNbm5yWXAvdWVKRWQxV2J2QVZuSjFzcTJrS2p1R1F6YkJZUHBramlCZVF1UHNHTS9tbXZXcUJzVHo1ClNGbWVVcDZ5TmU4aklRZEF1Qm9LOHhBZXRqVGE1SUZ3YUdQTi9vdkZGU3ZqakF3M1RWbEVqcXNDZ1lFQTBtdWEKa01IZUhhbjJodC9lMEVrSEZ1cGtqSExCM1pNUlhjTWFoSnh5YzVDc0h4MCtacnNaU0VPYnErK1JxTDh5UWNYYwpveXhremd5TnljZkovUm45NHpWRTRLRjJvVjA2bW1IYUdObWNwaGlQYWJQWXg3M1c1aktTaDhWbEpJdFpsR1NTCm1ZTHpGQ2QydGhIY0hiUThpalB6bUFEMHBOYUdnaEEreXNyWFRiVUNnWUVBcUFxalg0RlkvaExnTlFpR3lzMEYKckxpcGtEbndrQWNZeW9NLzlWV0MrVHB0czFScWhjZFV6RlU4UEV4RE1uNTN0bnZGUWM2TlR0eGxvYVlFOHlDNwp0R3VWdHFPWVBsK1ptRDh2QXNJYnRuSHJyN0kyRm15aWMwaERPeUtiYTl5QitrNEJqTDZ0TFQ3WFp0dFgzNklHCkI0MnhRUm9UOHZsM0IzM3pYVlY2bWRFQ2dZQXVsWTN4a0VvSlRUQjc2YUlkZ0oxbU1GdzBUOCtscTBLRC9JYXAKWnkxYmNtTDR2SE90TUt6SE45aUY5eExMUmhEdFNNMncva29PNSs2WUJuZ3NaWTIwdUgxWU1jYmVzSkloelpvSQpPRjBhMUlNamhxSnVqaE8rZ09HNTF6U3VJMytnZjZlSS90bXIwNVRQZUNMQUhML3VaTlFBQ2U0ZmRETHhKb0dRClNkbmlwUUtCZ0ZkWi8ra2JtdnhvSnUrR0pSS1BSSFZLRERwUytXT2xoMjhkZno5aTQzV1dFa3dYazNGTWZaV1gKS2FXc1Q4T3U5WGhXTHU5T1QzNU5LT3lsalJtNzFwdUZlZm12MmtyZEphS1MzaHZ6cmI3eVFCSmZVTFpQVzZOZgp4N3NMbndjbWUvdDVUeHo1bFNUeFRJTTVlcllEQUpyZ242TWFCaktWbitrTDNFWU5PRUZNCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURDakNDQWZLZ0F3SUJBZ0lKQVBqUVBZYVF1Zm1UTUEwR0NTcUdTSWIzRFFFQkJRVUFNQmd4RmpBVUJnTlYKQkFNVERXNW5jQzF3Y21sdFpYSXRZMkV3SGhjTk1UY3dOekU0TWpFME56VXhXaGNOTXpFd016STNNakUwTnpVeApXakFYTVJVd0V3WURWUVFEREF4amIyNTBZV04wY3kxaGNHa3dnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCCkR3QXdnZ0VLQW9JQkFRQ3ZySkNTSldXWGl0NFF1NVJHRXpGMkVtaDRXMFBEeG5SU2Y2QVQzdlN1VGJmd2RUUDMKaTBIWTd6d1RHYVg2bC9GMkpFVi9oMHNTOGhZY3JzakNNWVVtcG9OUnZDbGRGby9HdWZnK3U5ZVE0WG9xRlNWLwpCejNUU1pPVW1iUjAwWmdBWlJpejlpbE53TGliOHAzRVh0V1dvUy8zd21QTk5oamFiMHJYSXBvdG5KWWd4MmdOCkNINkw2M2x0ek1lOVJKWnpsWWp6S3dVb0s1Ykl5NURacndlMzR4UFZWcFNDQUZHaEZMTmk3eGZYRWkzUVZsNzAKUVJSOWVkMjFmL0tjSWUzNnFTaGd0MHhxOXNRbUpwa2ZaUE5RTlNXSWRFSGhGQ0NzU3VOWTFyRFh1ZEg0dVcycAplbEptSUdGL2xhNXozTFJqRDVuVnZLd2R5L2NCYTU1Ny8wM25BZ01CQUFHaldEQldNQWtHQTFVZEV3UUNNQUF3CkN3WURWUjBQQkFRREFnWGdNRHdHQTFVZEVRUTFNRE9DQTJGd2FZSU1ZWEJwTG1OdmJuUmhZM1J6Z2g1aGNHa3UKWTI5dWRHRmpkSE11YzNaakxtTnNkWE4wWlhJdWJHOWpZV3d3RFFZSktvWklodmNOQVFFRkJRQURnZ0VCQUJrZgpzeGRpdzExMlhmRXNLVGgvZVYwRm9oTURNM3JqcXVxaHdoU0lxbzdzeHlEbkZPV3dqY2ZNSDB4V05ZdGFheitpCnZlb3plVXNRTG5DREx1aEpnTGtzSjhaR1JDcTdjemZaRkZxSjdzL01OTnZVaUpWN0RCSlhHL0lEanFkbVIyWlEKcllTd3l0bVdkU1ZUVHp2UUFHZDUybjdaVGVqQVdLQ2RPU1F3UlFVRVVEZFJNNVZWak1mOFpUM05HdDFjbElXQQp3WjRVSlB4aGVuT3lscGlzWkxKK2Rub0l1YkV2dkF2UUZpU0dub0ZBekhjN3RIWHEweDlvV205WjR6Vm0rTm9SCkQ2OXJ5QzB3eXdTMFBsNE9URHJXOXdwQ0hXTkhTaEZkbTZoWDVmVXc5bllybERkNkd4OU9TdFVnUnhZS2EvSzcKNDFjTWpVdDhqa0JOd2lWaThYWT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
---
apiVersion: v1
kind: Secret
metadata:
  name: ca
  namespace: contacts
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURMRENDQWhTZ0F3SUJBZ0lKQU5HVWFRR0d2TVNlTUEwR0NTcUdTSWIzRFFFQkN3VUFNQmd4RmpBVUJnTlYKQkFNVERXNW5jQzF3Y21sdFpYSXRZMkV3SGhjTk1UY3dOak13TVRnMU5EQTJXaGNOTXpFd016QTVNVGcxTkRBMgpXakFZTVJZd0ZBWURWUVFERXcxdVozQXRjSEpwYldWeUxXTmhNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DCkFROEFNSUlCQ2dLQ0FRRUFzaDR5TStkNmdCR0VUelhpcGswdEJTaGNZWUhNbVRLVUwrZm8rei9rZ3RrMlNYMlYKcFVXK0tVVUxITURLVUEralU1RWI2VHBSNjFBMmdYNDlRaWxIZ2VYMzdLU2E5QVVQU2srbUgzM3FscXZlQ2gvSwoxREt5L3hLZTdONmxoeDRwbVhRV3h2WGZOdWg1eGM0NVpNYW1BM010UzE5OXZGMk1DaWFNSmxMOTJNMmRNSVFMCi9hUTluMjJRYXRKcUNyYlJNZTJlSGQ5aGFnTXh4NmtvbGpCaU5ZUXpXOTQ4bytLa0xNelE2UWE5MElrcnhXb2oKZ3JEaXlidmFqT2VndWlOd3E0eTFCZ2FWSEVTVGE3eUVJYkhLU1RWck1COXFUc0Nva0RzR1p6VXlUU1JnZU45NgpLM2tkRzMrVUkwOWFraDkxVVZ6ckpzVjlXMUxvYU1vUkNmQXI0UUlEQVFBQm8za3dkekFkQmdOVkhRNEVGZ1FVCjVGcDBSL1ArM0QvZWE1Ym9HRU85OVE1VE9YY3dTQVlEVlIwakJFRXdQNEFVNUZwMFIvUCszRC9lYTVib0dFTzkKOVE1VE9YZWhIS1FhTUJneEZqQVVCZ05WQkFNVERXNW5jQzF3Y21sdFpYSXRZMkdDQ1FEUmxHa0JocnpFbmpBTQpCZ05WSFJNRUJUQURBUUgvTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFDZE81aEVSRWViWjNKYjk0QzJkT2pxCkNoVmtycUl4OTgvYmFSOHppZTJXUmUzRU1YV2I3ei9rOUVGanhsRWxXQkhOL1FpdFZUZzhNeElNd0RFVGZ1TjkKcVBaRE85OE9GRXZZZWxwaTdlM0x3NVlQd2hBT1hBa2laUHFjQ0tZRlRvbFFod3kvQnpvRVpCbmdXK052VkNpWgp6My9XYmMvRmlwUmNwdGVFaUZEL2d3bUFoaFJnYlpjM0NaRHRhUmVBdWRqUjAwY3F2amlLU0d2N0dCMU4zT0xsClpvZEpTd3NBT2lDVGNBMHMwQ0FlNndHaWVOOFhBRnhiYlZhSWpkblRtNUFmWkdsZ0E2cVBjQTU0R1loVE5FTFoKZzlDODdYK2t0SDdLeEFSYndQV0RjcmJnMEI0bGFDYjE0RlRLWnYzVUQ5K2Nqb3p3QXREWXVTQUtKRWdxYnNLYgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
type: Opaque
